CREATE TABLE IF NOT EXISTS base_system_users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	roles TEXT NOT NULL DEFAULT '[]',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS base_system_sessions (
	id VARCHAR(128) PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES base_system_users(id) ON DELETE CASCADE,
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS base_system_sessions_user_id ON base_system_sessions(user_id);

CREATE TABLE IF NOT EXISTS base_system_configs (
	"key" VARCHAR(255) PRIMARY KEY,
	value TEXT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS base_system_bootstrap (
	"key" VARCHAR(255) PRIMARY KEY,
	value TEXT NOT NULL
);
INSERT INTO base_system_bootstrap ("key", value) VALUES ('initial_admin', 'open') ON CONFLICT ("key") DO NOTHING;

CREATE TABLE IF NOT EXISTS base_oidc_login_requests (
	id VARCHAR(128) PRIMARY KEY,
	issuer TEXT NOT NULL,
	state VARCHAR(255) NOT NULL UNIQUE,
	nonce VARCHAR(255) NOT NULL,
	code_verifier VARCHAR(255) NOT NULL,
	return_path TEXT NOT NULL DEFAULT '/',
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS base_oidc_accounts (
	issuer VARCHAR(512) NOT NULL,
	subject VARCHAR(512) NOT NULL,
	user_id BIGINT NOT NULL REFERENCES base_system_users(id) ON DELETE CASCADE,
	profile TEXT NOT NULL DEFAULT '{}',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	PRIMARY KEY (issuer, subject)
);
CREATE INDEX IF NOT EXISTS base_oidc_accounts_user ON base_oidc_accounts(user_id);

CREATE TABLE IF NOT EXISTS base_oidc_sessions (
	issuer VARCHAR(512) NOT NULL,
	sid VARCHAR(255) NOT NULL,
	session_id VARCHAR(128) NOT NULL UNIQUE REFERENCES base_system_sessions(id) ON DELETE CASCADE,
	created_at BIGINT NOT NULL,
	PRIMARY KEY (issuer, sid)
);
