CREATE TABLE IF NOT EXISTS global_sites (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	site_key VARCHAR(64) NOT NULL UNIQUE CHECK (site_key ~ '^[a-z][a-z0-9_]*$'),
	name VARCHAR(255) NOT NULL,
	base_site_key VARCHAR(64),
	dsn TEXT NOT NULL DEFAULT '',
	dsn_password TEXT,
	database_binding VARCHAR(64) NOT NULL DEFAULT '',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	migration_status VARCHAR(32) NOT NULL DEFAULT 'ready',
	is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
	is_system SMALLINT NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1)),
	passport_sso_enabled SMALLINT NOT NULL DEFAULT 0 CHECK (passport_sso_enabled IN (0, 1))
);
CREATE UNIQUE INDEX IF NOT EXISTS global_sites_one_default ON global_sites(is_default) WHERE is_default = 1 AND status = 'enabled';

CREATE TABLE IF NOT EXISTS global_site_hosts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	hostname VARCHAR(255) NOT NULL UNIQUE,
	site_key VARCHAR(64) NOT NULL REFERENCES global_sites(site_key),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	created_at BIGINT NOT NULL
);

INSERT INTO global_sites (site_key, name, base_site_key, dsn, status, migration_status, is_default, is_system)
	VALUES ('global', '全局控制面', 'base', '', 'enabled', 'ready', 1, 1)
	ON CONFLICT (site_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS global_cloud_credentials (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	provider VARCHAR(64) NOT NULL,
	account_id VARCHAR(255) NOT NULL DEFAULT '',
	access_key_id VARCHAR(512) NOT NULL DEFAULT '',
	access_key_secret TEXT NOT NULL DEFAULT '',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS global_cloud_object_storage_buckets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cloud_credential_id BIGINT NOT NULL REFERENCES global_cloud_credentials(id) ON DELETE RESTRICT,
	endpoint TEXT NOT NULL,
	region VARCHAR(255) NOT NULL DEFAULT '',
	bucket VARCHAR(255) NOT NULL,
	path_style SMALLINT NOT NULL DEFAULT 0 CHECK (path_style IN (0, 1)),
	public_base_url TEXT NOT NULL DEFAULT '',
	extra_config TEXT NOT NULL DEFAULT '{}',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (cloud_credential_id, endpoint, bucket)
);

CREATE TABLE IF NOT EXISTS global_cloud_object_storage_bindings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	site_key VARCHAR(64) NOT NULL REFERENCES global_sites(site_key) ON DELETE CASCADE,
	bucket_id BIGINT NOT NULL REFERENCES global_cloud_object_storage_buckets(id) ON DELETE RESTRICT,
	key_prefix TEXT NOT NULL DEFAULT '',
	status VARCHAR(32) NOT NULL DEFAULT 'enabled',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (id, site_key),
	UNIQUE (site_key, bucket_id, key_prefix)
);

CREATE TABLE IF NOT EXISTS global_cloud_object_storage_binding_purposes (
	binding_id BIGINT NOT NULL,
	site_key VARCHAR(64) NOT NULL,
	purpose VARCHAR(64) NOT NULL,
	is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
	PRIMARY KEY (binding_id, purpose),
	FOREIGN KEY (binding_id, site_key) REFERENCES global_cloud_object_storage_bindings(id, site_key) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS global_cloud_object_storage_binding_purposes_one_default ON global_cloud_object_storage_binding_purposes(site_key, purpose) WHERE is_default = 1;

CREATE TABLE IF NOT EXISTS global_telegram_bots (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE CHECK (LENGTH(TRIM(name)) > 0),
	bot_token VARCHAR(255) NOT NULL UNIQUE CHECK (LENGTH(TRIM(bot_token)) > 0),
	bot_username VARCHAR(255) NOT NULL UNIQUE CHECK (LENGTH(TRIM(bot_username)) > 0),
	secret_token VARCHAR(256) NOT NULL CHECK (LENGTH(TRIM(secret_token)) BETWEEN 1 AND 256),
	webhook_hostname VARCHAR(255) NOT NULL REFERENCES global_site_hosts(hostname) ON DELETE RESTRICT ON UPDATE RESTRICT,
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS global_telegram_bots_webhook_hostname ON global_telegram_bots(webhook_hostname);

CREATE TABLE IF NOT EXISTS global_cloud_email_channels (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cloud_credential_id BIGINT NOT NULL REFERENCES global_cloud_credentials(id) ON DELETE RESTRICT,
	region VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(region)) > 0),
	account_name VARCHAR(320) NOT NULL CHECK (LENGTH(TRIM(account_name)) > 0),
	from_alias VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(from_alias)) > 0),
	reply_to_address SMALLINT NOT NULL DEFAULT 0 CHECK (reply_to_address IN (0, 1)),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (cloud_credential_id, region, account_name)
);

CREATE TABLE IF NOT EXISTS global_cloud_email_templates (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	template_key VARCHAR(128) NOT NULL UNIQUE CHECK (template_key ~ '^[a-z][a-z0-9_]*$'),
	template_type VARCHAR(64) NOT NULL DEFAULT 'email_verification' CHECK (template_type IN ('email_verification')),
	name VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(name)) > 0),
	subject TEXT NOT NULL CHECK (LENGTH(TRIM(subject)) > 0),
	body_text TEXT NOT NULL CHECK (LENGTH(TRIM(body_text)) > 0),
	body_html TEXT NOT NULL CHECK (LENGTH(TRIM(body_html)) > 0),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS global_cloud_email_bindings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	site_key VARCHAR(64) NOT NULL REFERENCES global_sites(site_key) ON DELETE RESTRICT,
	channel_id BIGINT NOT NULL REFERENCES global_cloud_email_channels(id) ON DELETE RESTRICT,
	template_id BIGINT NOT NULL REFERENCES global_cloud_email_templates(id) ON DELETE RESTRICT,
	purpose VARCHAR(64) NOT NULL CHECK (LENGTH(TRIM(purpose)) > 0),
	is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (site_key, channel_id, template_id, purpose)
);
CREATE UNIQUE INDEX IF NOT EXISTS global_cloud_email_bindings_one_default ON global_cloud_email_bindings(site_key, purpose) WHERE is_default = 1 AND status = 'enabled';

CREATE TABLE IF NOT EXISTS global_cloud_email_template_publications (
	template_id BIGINT NOT NULL REFERENCES global_cloud_email_templates(id) ON DELETE RESTRICT,
	cloud_credential_id BIGINT NOT NULL REFERENCES global_cloud_credentials(id) ON DELETE RESTRICT,
	region VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(region)) > 0),
	provider_template_id VARCHAR(255) NOT NULL CHECK (LENGTH(TRIM(provider_template_id)) > 0),
	content_hash TEXT NOT NULL DEFAULT '',
	status VARCHAR(32) NOT NULL CHECK (status IN ('reviewing', 'ready', 'rejected', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	PRIMARY KEY (template_id, cloud_credential_id, region)
);
