CREATE TABLE IF NOT EXISTS passport_users (
	user_id BIGINT PRIMARY KEY CHECK (user_id >= 4194304),
	nickname VARCHAR(48) NOT NULL CHECK (LENGTH(TRIM(nickname)) BETWEEN 1 AND 12),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_user_credentials (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	password TEXT NOT NULL CHECK (LENGTH(TRIM(password)) > 0),
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_user_credentials_user_created ON passport_user_credentials(user_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS passport_sessions (
	id VARCHAR(128) PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_sessions_user_id ON passport_sessions(user_id);
CREATE INDEX IF NOT EXISTS passport_sessions_expires_at ON passport_sessions(expires_at);

CREATE TABLE IF NOT EXISTS passport_telegram_accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	bot_id BIGINT NOT NULL,
	telegram_user_id BIGINT NOT NULL,
	chat_id BIGINT NOT NULL,
	nickname VARCHAR(48) NOT NULL CHECK (LENGTH(TRIM(nickname)) BETWEEN 1 AND 12),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (user_id, bot_id, telegram_user_id),
	UNIQUE (bot_id, telegram_user_id)
);

CREATE TABLE IF NOT EXISTS passport_oauth_accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	provider VARCHAR(64) NOT NULL,
	provider_user_id VARCHAR(512) NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (user_id, provider, provider_user_id),
	UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS passport_emails (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(320) NOT NULL UNIQUE,
	verified SMALLINT NOT NULL DEFAULT 0 CHECK (verified IN (0, 1)),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_user_emails (
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	email_id BIGINT NOT NULL UNIQUE REFERENCES passport_emails(id) ON DELETE RESTRICT,
	is_primary SMALLINT NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
	created_at BIGINT NOT NULL,
	PRIMARY KEY (user_id, email_id)
);

CREATE TABLE IF NOT EXISTS passport_email_otp (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bot_id BIGINT NOT NULL,
	telegram_user_id BIGINT NOT NULL,
	chat_id BIGINT NOT NULL,
	email VARCHAR(320) NOT NULL,
	code_hash TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
	status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'used', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_email_otp_lookup ON passport_email_otp(bot_id, telegram_user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS passport_user_roles (
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	role VARCHAR(128) NOT NULL,
	created_at BIGINT NOT NULL,
	PRIMARY KEY (user_id, role)
);

CREATE TABLE IF NOT EXISTS passport_group_prompts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chat_id BIGINT NOT NULL,
	actor_id BIGINT NOT NULL,
	state_json TEXT NOT NULL DEFAULT '{}',
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_group_prompts_lookup ON passport_group_prompts(chat_id, actor_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS passport_snowflake_state (
	worker_id INTEGER PRIMARY KEY CHECK (worker_id BETWEEN 0 AND 1023),
	last_timestamp BIGINT NOT NULL CHECK (last_timestamp >= 1288834974657),
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_telegram_menus (
	bot_id BIGINT NOT NULL,
	telegram_user_id BIGINT NOT NULL,
	chat_id BIGINT NOT NULL,
	message_id BIGINT NOT NULL,
	mode VARCHAR(16) NOT NULL CHECK (mode IN ('menu', 'email', 'otp')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	PRIMARY KEY (bot_id, telegram_user_id)
);

CREATE TABLE IF NOT EXISTS passport_telegram_updates (
	bot_id BIGINT NOT NULL,
	update_id BIGINT NOT NULL,
	status VARCHAR(32) NOT NULL CHECK (status IN ('processing', 'completed', 'failed')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	PRIMARY KEY (bot_id, update_id)
);
CREATE INDEX IF NOT EXISTS passport_telegram_updates_status ON passport_telegram_updates(status, updated_at);

CREATE TABLE IF NOT EXISTS passport_telegram_identity_choices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bot_id BIGINT NOT NULL,
	telegram_user_id BIGINT NOT NULL,
	chat_id BIGINT NOT NULL,
	target_user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	email VARCHAR(320) NOT NULL,
	status VARCHAR(32) NOT NULL CHECK (status IN ('pending', 'confirmed', 'cancelled', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_telegram_identity_choices_lookup ON passport_telegram_identity_choices(bot_id, telegram_user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS passport_login_challenges (
	id VARCHAR(128) PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	bot_id BIGINT NOT NULL,
	telegram_user_id BIGINT NOT NULL,
	chat_id BIGINT NOT NULL,
	expected_number INTEGER NOT NULL CHECK (expected_number BETWEEN 1 AND 99),
	status VARCHAR(32) NOT NULL CHECK (status IN ('pending', 'approved', 'denied', 'expired', 'consumed')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_login_challenges_identity ON passport_login_challenges(bot_id, telegram_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS passport_login_challenges_expires ON passport_login_challenges(status, expires_at);

CREATE TABLE IF NOT EXISTS passport_sso_requests (
	id VARCHAR(128) PRIMARY KEY,
	target_site_key VARCHAR(64) NOT NULL,
	target_hostname VARCHAR(255) NOT NULL,
	status VARCHAR(32) NOT NULL CHECK (status IN ('pending', 'consumed', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_sso_requests_expires ON passport_sso_requests(status, expires_at);

CREATE TABLE IF NOT EXISTS passport_login_tickets (
	token_hash CHAR(64) PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	target_site_key VARCHAR(64) NOT NULL,
	target_hostname VARCHAR(255) NOT NULL,
	status VARCHAR(32) NOT NULL CHECK (status IN ('pending', 'consumed', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_login_tickets_expires ON passport_login_tickets(status, expires_at);

CREATE TABLE IF NOT EXISTS passport_site_sessions (
	id VARCHAR(128) PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE RESTRICT,
	site_key VARCHAR(64) NOT NULL,
	hostname VARCHAR(255) NOT NULL,
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_site_sessions_user ON passport_site_sessions(user_id);
CREATE INDEX IF NOT EXISTS passport_site_sessions_target ON passport_site_sessions(site_key, hostname, expires_at);

CREATE TABLE IF NOT EXISTS passport_external_identities (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE CASCADE,
	provider VARCHAR(64) NOT NULL,
	subject VARCHAR(512) NOT NULL,
	profile TEXT NOT NULL DEFAULT '{}',
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL,
	UNIQUE (provider, subject)
);
CREATE INDEX IF NOT EXISTS passport_external_identities_user ON passport_external_identities(user_id);

CREATE TABLE IF NOT EXISTS passport_oidc_clients (
	id VARCHAR(128) PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	secret_hash CHAR(64) NOT NULL,
	redirect_uris TEXT NOT NULL DEFAULT '[]',
	backchannel_logout_uri TEXT NOT NULL DEFAULT '',
	allowed_scopes TEXT NOT NULL DEFAULT 'openid profile email',
	require_pkce SMALLINT NOT NULL DEFAULT 1 CHECK (require_pkce IN (0, 1)),
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_oidc_authorization_requests (
	id VARCHAR(128) PRIMARY KEY,
	client_id VARCHAR(128) NOT NULL REFERENCES passport_oidc_clients(id) ON DELETE CASCADE,
	redirect_uri TEXT NOT NULL,
	scope TEXT NOT NULL,
	state TEXT NOT NULL DEFAULT '',
	nonce TEXT NOT NULL DEFAULT '',
	code_challenge TEXT NOT NULL DEFAULT '',
	code_challenge_method VARCHAR(32) NOT NULL DEFAULT '',
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_oidc_authorization_codes (
	code_hash CHAR(64) PRIMARY KEY,
	client_id VARCHAR(128) NOT NULL REFERENCES passport_oidc_clients(id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE CASCADE,
	redirect_uri TEXT NOT NULL,
	scope TEXT NOT NULL,
	nonce TEXT NOT NULL DEFAULT '',
	code_challenge TEXT NOT NULL DEFAULT '',
	code_challenge_method VARCHAR(32) NOT NULL DEFAULT '',
	expires_at BIGINT NOT NULL,
	consumed_at BIGINT,
	created_at BIGINT NOT NULL,
	session_id VARCHAR(128) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS passport_oidc_codes_expiry ON passport_oidc_authorization_codes(expires_at, consumed_at);

CREATE TABLE IF NOT EXISTS passport_oidc_access_tokens (
	token_hash CHAR(64) PRIMARY KEY,
	client_id VARCHAR(128) NOT NULL REFERENCES passport_oidc_clients(id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES passport_users(user_id) ON DELETE CASCADE,
	scope TEXT NOT NULL,
	expires_at BIGINT NOT NULL,
	revoked_at BIGINT,
	created_at BIGINT NOT NULL,
	session_id VARCHAR(128) NOT NULL DEFAULT '',
	authorization_code_hash CHAR(64) UNIQUE
);
CREATE INDEX IF NOT EXISTS passport_oidc_tokens_expiry ON passport_oidc_access_tokens(expires_at, revoked_at);

CREATE TABLE IF NOT EXISTS passport_oidc_signing_keys (
	kid VARCHAR(255) PRIMARY KEY,
	private_jwk TEXT NOT NULL,
	public_jwk TEXT NOT NULL,
	status VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
	created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_external_providers (
	id VARCHAR(32) PRIMARY KEY CHECK (id IN ('google', 'wechat')),
	display_name VARCHAR(255) NOT NULL,
	client_id VARCHAR(512) NOT NULL,
	client_secret TEXT NOT NULL,
	status VARCHAR(32) NOT NULL DEFAULT 'enabled' CHECK (status IN ('enabled', 'disabled')),
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_external_login_states (
	id_hash CHAR(64) PRIMARY KEY,
	provider VARCHAR(32) NOT NULL REFERENCES passport_external_providers(id) ON DELETE RESTRICT,
	code_verifier TEXT NOT NULL,
	nonce TEXT NOT NULL,
	redirect_uri TEXT NOT NULL,
	expires_at BIGINT NOT NULL,
	consumed_at BIGINT,
	created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_external_login_states_expiry ON passport_external_login_states(expires_at, consumed_at);

CREATE TABLE IF NOT EXISTS passport_external_pending_identities (
	id_hash CHAR(64) PRIMARY KEY,
	provider VARCHAR(32) NOT NULL REFERENCES passport_external_providers(id) ON DELETE RESTRICT,
	subject VARCHAR(512) NOT NULL,
	nickname VARCHAR(255) NOT NULL,
	profile TEXT NOT NULL,
	status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS passport_external_email_otps (
	id VARCHAR(128) PRIMARY KEY,
	pending_identity_hash CHAR(64) NOT NULL REFERENCES passport_external_pending_identities(id_hash) ON DELETE CASCADE,
	email VARCHAR(320) NOT NULL,
	code_hash TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0,
	status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'used', 'expired')),
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL,
	updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS passport_external_email_otps_lookup ON passport_external_email_otps(pending_identity_hash, status, created_at);
